### ISSUE TITLE
Persist data with Room

### ISSUE THREAD

**Issue by bmaum321** [google-developer-training/basic-android-kotlin-compose-training-inventory-app#2]
**URL of codelab:**
https://developer.android.com/codelabs/basic-android-kotlin-compose-persisting-data-room?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-7-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-persisting-data-room#11

**Specify the language of the codelab if it is not English:**

**In which task and step of the codelab can this issue be found?**
N/A

**Describe the problem**
The Workmanager Unit 7 codelabs point to the wrong URL.  They both point to to the Room codelab found here https://developer.android.com/codelabs/basic-android-kotlin-compose-persisting-data-room?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-7-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-persisting-data-room#0

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_
_API version of the emulator:_
N/A

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
Hello @bmaum321,

Thanks a lot for reporting this issue! It slipped while we were trying to publish a new codelab before holidays))
It will be fixed shortly.
