### ISSUE TITLE
Persist data with Room

### ISSUE THREAD

**Issue by RaczkaKamil** [google-developer-training/basic-android-kotlin-compose-training-inventory-app#3]
Hello Googlers!

When I try to make Unit 7, button in lesson 3 ('Background work with WorkManager') redirects to Room lessons

I'm not sure if it is an bug, or that is because I completed Room lessons in 'Android Basics in Kotlin' course, instead of  'New! Android Basics with Compose' course

Anyway, have a lovely day!

**URL of codelab:**

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/38607018/209875658-ae9fdb86-3a38-4898-92a0-898d36b09f19.png">

**Specify the language of the codelab if it is not English:**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_
_API version of the emulator:_

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
Hello @RaczkaKamil, 
Good catch! Thanks a lot for reporting this. We'll definitely will fix.
