### ISSUE TITLE
Persist data with Room

### ISSUE THREAD

**Issue by wngu6** [google-developer-training/basic-android-kotlin-compose-training-inventory-app#6]
**URL of codelab:**

**Specify the language of the codelab if it is not English:**

**In which task and step of the codelab can this issue be found?**
5. Create an item Entity, Data Classes: Step 2

**Describe the problem**
The `tableName` in `@Entity(tableName = "items")` should be `@Entity(tableName = "item")`, otherwise the following error will occur during build:
```
There is a problem with the query: [SQLITE_ERROR] SQL error or missing database (no such table: item)
```
**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_
_API version of the emulator:_

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by PICO443** [comment]
The `tableName` should be "Item" not "Items" following the note from the previous codelab:

> Note: Like with Kotlin classes, the convention is to use the singular form for the name of database tables. For the example above, that means you name the tables teacher, student, and course, not the plural forms of teachers, students, and courses.

**Comment by lyay** [comment]
> Note: Like with Kotlin classes, the convention is to use the singular form for the name of database tables.
Тогда переименуйте таблицу в [5. Create an item Entity](https://developer.android.com/codelabs/basic-android-kotlin-compose-persisting-data-room#4) !

@Entity(tableName = "items")
data class Item(
   ...
)

Странно, конечно, использовать единственное число для сущности, содержащей много предметов. Раз уж приняли правило, так применяйте везде. В текущем виде пример не работоспособен.

**Comment by fe60** [comment]
Course containing the note about table naming convention mentioned by @PICO443 [above](https://github.com/google-developer-training/basic-android-kotlin-compose-training-inventory-app/issues/6#issuecomment-1403233108).
https://developer.android.com/codelabs/basic-android-kotlin-compose-sql#1

Inconsistent naming of database tables can be found in [Android Room guide](https://developer.android.com/training/data-storage/room/) too. For the [definition of entities](https://developer.android.com/training/data-storage/room/defining-data) it uses a plural word for table name, while the example shows singular naming in a query for [accessing the data](https://developer.android.com/training/data-storage/room/accessing-data).

**Comment by osuleymanova** [comment]
Hello @wngu6,

Thank you for reaching out to us. It is fixed and published.
